# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  #config.vm.box = "debian/jessie64"
  config.vm.box = "cargomedia/debian-8-amd64-plain"
  #config.vm.provision "puppet" do |puppet|
  #	puppet.manifests_path = "vagrant_manifests"
  #	puppet.manifest_file = "default.pp"
  #end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "128"
  end

  config.vm.define "master" do |node|
        node.vm.hostname = "master.lab.itmz.pl"
  	node.vm.provision "shell", inline: "apt-get install puppet -y"
  	node.vm.provision "puppet" 
        node.vm.network "private_network", ip: "192.168.21.253"
	node.vm.synced_folder "puppetmaster", "/etc/puppet", owner: "root", group: "root"
  end

  config.vm.define "vs" do |node|
        node.vm.hostname = "vs.lab.itmz.pl"
  	node.vm.provision "shell", inline: "apt-get install puppet -y"
  	node.vm.provision "puppet" 
        node.vm.network "private_network", ip: "192.168.21.100"
        node.vm.network "private_network", ip: "10.33.32.11", auto_config: false #fake for eth2
        node.vm.network "private_network", ip: "10.33.33.12", auto_config: false #fake for eth3
        node.vm.network "private_network", ip: "10.33.34.13", auto_config: false #fake for eth4
  end

  config.vm.define "vc" do |node|
        node.vm.hostname = "vc.lab.itmz.pl"
  	node.vm.provision "shell", inline: "apt-get install puppet -y"
  	node.vm.provision "puppet" 
        node.vm.network "private_network", ip: "192.168.21.200"
        node.vm.network "private_network", ip: "10.33.32.21", auto_config: false #fake for eth2
        node.vm.network "private_network", ip: "10.33.33.22", auto_config: false #fake for eth3
        node.vm.network "private_network", ip: "10.33.34.23", auto_config: false #fake for eth4
  end

  config.vm.define "n1a" do |node|
        node.vm.hostname = "n1a.lab.itmz.pl"
  	node.vm.provision "shell", inline: "apt-get install puppet -y"
  	node.vm.provision "puppet" 
        node.vm.network "private_network", ip: "192.168.21.11"
        node.vm.network "private_network", ip: "10.33.32.31", auto_config: false #fake for eth2
  end

  config.vm.define "n1b" do |node|
       node.vm.hostname = "n1b.lab.itmz.pl"
  	node.vm.provision "shell", inline: "apt-get install puppet -y"
  	node.vm.provision "puppet" 
        node.vm.network "private_network", ip: "192.168.21.12"
        node.vm.network "private_network", ip: "10.33.32.41", auto_config: false #fake for eth2
  end

  config.vm.define "n2a" do |node|
        node.vm.hostname = "n2a.lab.itmz.pl"
  	node.vm.provision "shell", inline: "apt-get install puppet -y"
  	node.vm.provision "puppet" 
        node.vm.network "private_network", ip: "192.168.21.21"
        node.vm.network "private_network", ip: "10.33.32.51", auto_config: false #fake for eth2
        node.vm.network "private_network", ip: "10.33.33.52", auto_config: false #fake for eth3
  end

  config.vm.define "n2b" do |node|
       node.vm.hostname = "n2b.lab.itmz.pl"
  	node.vm.provision "shell", inline: "apt-get install puppet -y"
  	node.vm.provision "puppet" 
        node.vm.network "private_network", ip: "192.168.21.22"
        node.vm.network "private_network", ip: "10.33.32.61", auto_config: false #fake for eth2
        node.vm.network "private_network", ip: "10.33.33.62", auto_config: false #fake for eth3
  end


  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
  

end
