# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  #config.vm.box = "debian/jessie64"
  config.vm.box = "cargomedia/debian-8-amd64-plain"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "128"
  end

  config.vm.define "node41" do |node|
        node.vm.hostname = "node41.lab.itmz.pl"
  	node.vm.provision "shell", inline: "apt-get install puppet -y"
  	node.vm.provision "puppet" 
        node.vm.network "private_network", ip: "192.168.41.41"
        node.vm.network "private_network", ip: "192.168.42.41", auto_config: false
        node.vm.network "private_network", ip: "192.168.43.41", auto_config: false
        node.vm.network "private_network", ip: "192.168.44.41", auto_config: false
  end

  config.vm.define "node42" do |node|
        node.vm.hostname = "node42.lab.itmz.pl"
  	node.vm.provision "shell", inline: "apt-get install puppet -y"
  	node.vm.provision "puppet" 
        node.vm.network "private_network", ip: "192.168.41.42"
        node.vm.network "private_network", ip: "192.168.42.42", auto_config: false
        node.vm.network "private_network", ip: "192.168.43.42", auto_config: false
        node.vm.network "private_network", ip: "192.168.44.42", auto_config: false
  end

  config.vm.define "node43" do |node|
        node.vm.hostname = "node43.lab.itmz.pl"
	node.vm.box = "geerlingguy/centos7"
  	node.vm.provision "shell", inline: "sudo yum install -y puppet; sleep 10"
  	node.vm.provision "puppet" 
        node.vm.network "private_network", ip: "192.168.41.43"
        node.vm.network "private_network", ip: "192.168.42.43", auto_config: false
        node.vm.network "private_network", ip: "192.168.43.43", auto_config: false
        node.vm.network "private_network", ip: "192.168.44.43", auto_config: false
        node.vm.provision "shell", inline: "systemctl restart network.service"
  end

  config.vm.define "node44" do |node|
        node.vm.hostname = "node44.lab.itmz.pl"
	node.vm.box = "geerlingguy/centos7"
  	node.vm.provision "shell", inline: "sudo yum install -y puppet; sleep 10"
  	node.vm.provision "puppet" 
        node.vm.network "private_network", ip: "192.168.41.44"
        node.vm.network "private_network", ip: "192.168.42.44", auto_config: false
        node.vm.network "private_network", ip: "192.168.43.44", auto_config: false
        node.vm.network "private_network", ip: "192.168.44.44", auto_config: false
        node.vm.provision "shell", inline: "systemctl restart network.service"
  end

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
  

end
